# Generated by Django 3.2.6 on 2021-09-06 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(editable=False, max_length=20)),
                ('LastName', models.CharField(editable=False, max_length=20)),
                ('Email', models.EmailField(editable=False, max_length=50)),
                ('Password', models.CharField(editable=False, max_length=64)),
                ('Mobile', models.CharField(editable=False, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('Address1', models.TextField(editable=False, max_length=100, verbose_name='Address')),
                ('Address2', models.TextField(blank=True, editable=False, max_length=100, verbose_name='Alternative Address')),
                ('Status', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='2', max_length=1)),
            ],
        ),
    ]
