# Generated by Django 3.2.6 on 2021-10-17 12:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('BrandName', models.CharField(max_length=50)),
                ('Status', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=50)),
                ('Status', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Userx',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(editable=False, max_length=64)),
                ('Mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('Address1', models.TextField(max_length=100, verbose_name='Address')),
                ('Address2', models.TextField(blank=True, max_length=100, verbose_name='Alternative Address')),
                ('Type', models.CharField(default='c', max_length=1)),
                ('Status', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='2', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Desc', models.TextField()),
                ('Image', models.ImageField(upload_to='FarmersBuddy/products/')),
                ('Price', models.PositiveBigIntegerField()),
                ('Quantity', models.PositiveIntegerField()),
                ('Keywords', models.TextField(max_length=50)),
                ('Status', models.CharField(default='1', max_length=1)),
                ('ProductBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmersBuddy.brand')),
                ('ProductCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmersBuddy.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('Status', models.CharField(default='0', max_length=1)),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmersBuddy.product')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmersBuddy.userx')),
            ],
        ),
    ]
