# Generated by Django 3.2.6 on 2021-10-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersBuddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.IntegerField()),
                ('Quantity', models.PositiveIntegerField(default=1)),
                ('TotalAmount', models.PositiveIntegerField()),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmersBuddy.product')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmersBuddy.userx')),
            ],
        ),
    ]
