# Generated by Django 3.2.6 on 2021-09-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersBuddy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User',
        ),
    ]
