# Generated by Django 3.2.6 on 2021-10-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersBuddy', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ProductId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='UserId',
        ),
        migrations.AlterField(
            model_name='userx',
            name='Password',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
