# Generated by Django 3.2.6 on 2021-09-06 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersBuddy', '0002_rename_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userx',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(editable=False, max_length=64)),
                ('Mobile', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$')])),
                ('Address1', models.TextField(max_length=100, verbose_name='Address')),
                ('Address2', models.TextField(blank=True, max_length=100, verbose_name='Alternative Address')),
                ('Status', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='2', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
