# Generated by Django 3.2.6 on 2021-10-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersBuddy', '0003_auto_20211018_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.TextField()),
                ('Status', models.CharField(default='0', max_length=1)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmersBuddy.userx')),
            ],
        ),
    ]
