# Generated by Django 3.2.6 on 2021-10-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersBuddy', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
