# Generated by Django 3.2.6 on 2021-10-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersBuddy', '0005_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Address',
            field=models.TextField(default='bardoli'),
            preserve_default=False,
        ),
    ]
