# Generated by Django 3.2.6 on 2021-09-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersBuddy', '0005_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=50)),
                ('Status', models.CharField(default='1', max_length=1)),
            ],
        ),
    ]
