# Generated by Django 3.2.6 on 2021-10-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersBuddy', '0006_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField(max_length=100)),
                ('Desc', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(default='1', max_length=1)),
            ],
        ),
    ]
