# Generated by Django 3.2.6 on 2021-10-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersBuddy', '0008_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
