# Generated by Django 3.2.6 on 2021-10-25 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FarmersBuddy', '0009_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField(max_length=100)),
                ('Desc', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmersBuddy.userx')),
            ],
        ),
    ]
